name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v2
    - run: cargo build
    - run: cargo test

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v2
    - run: cargo fmt -- --check
